---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: registry.suse.com/bci/bci-base:15.4
  environment:
    TARGETPLATFORM: x86_64-unknown-linux-gnu
  commands:
  - ./scripts/ci

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/k3s-main
    - refs/tags/*
    event:
    - tag
